### ISSUE TITLE
Wildcard media type handling

### ISSUE THREAD

**Issue by timothyqiu** [di/flask-accept#3]
Hi,

I noticed that Flask-Accept is generating 406 Not Acceptable for wildcard media types.

```
@app.route('/')
@accept('application/json')
def index():
    return 'OK'
```

The example above generates 406 for `Accept: application/*`, `Accept: */*`, and when no Accept header is present, which essentially means `Accept: */*`.

According to RFC 2616, `*/*` means all media types are acceptable and `application/*` means all subtypes of `application` are acceptable, both accepts `application/json`. So it might be a bug for Flask-Accept to generate 406.

p.s. There's a test case that requires a 406 for `*/*` which I believe is wrong.

**Comment by di** [comment]
Hi @timothyqiu, thanks for reporting this issue! What you are describing is actually by design, so I'll try to explain this here and use the issue to make the documentation more clear.

To continue your example, let's imagine we had a second header which the app would support:

``` python
@app.route('/')
@accept('application/json')
def index():
    return 'JSON'

@index.support('text/html')
def index_html():
    return 'HTML'
```

Flask-Accept has no notion of header precedence, so If we sent a request with `Accept: */*`, it would not be clear which result we should get. Thus, you get a `406 Not Acceptable`.

If you wanted your app to not do this for `Accept: application/*`, `Accept: application/*`, and `Accept: */*`, you could modify it as follows:

``` python
@app.route('/')
@accept('*/*')
def index():
    return 'OK'
```

And if you wanted it to handle the case of missing headers as well:

``` python
@app.route('/')
@accept_fallback
def index():
    return 'OK'
```

I hope that makes things more clear!

**Comment by timothyqiu** [comment]
Explicitly accepting wildcard types is a reasonable solution to the problem. Thank you for your detailed explanation :)
